# Dockerfile
FROM haskell:latest

# Install additional dependencies if needed
# RUN apt-get update && apt-get install -y <package_name>

# Set working directory
WORKDIR /workspace

# Copy project files to the container
COPY . /workspace